name: Crowdin Action

on:
  push:
    branches: [ 'mkj/crowdin' ]
  schedule:
    - cron: '27 7 * * *' # daily at 07:27 (UTC)
  workflow_dispatch:

jobs:
  synchronize-with-crowdin:
    runs-on: ubuntu-latest

    strategy:
      max-parallel: 1

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download translations
        uses: crowdin/github-action@v2
        with:
          upload_sources: false
          upload_translations: false
          download_sources: true
          download_translations: true
          localization_branch_name: l10n_crowdin_translations
          create_pull_request: true
          pull_request_title: 'New Crowdin Translations'
          pull_request_body: 'New Crowdin translations by [Crowdin GH Action](https://github.com/crowdin/github-action)'
          pull_request_base_branch_name: 'mkj/crowdin'
          pull_request_labels: 'i18n, automated'
          pull_request_reviewers: mtbitcr
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
